# --------------------
# Define default values
# --------------------

# ==================== Alas ====================


# ==================== Farm ====================


# ==================== Daily ====================


# ==================== Tools ====================
